# Site settings
title: Danny Berghoff
header-img: 
email: dberghoff2@gmail.com
copyright_name: Danny Berghoff
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: ""
url: "http://yourdomain.com"
#twitter_username: SBootstrap
#github_username:  djberghoff
#facebook_username:  StartBootstrap
email_username:  dberghoff2@gmail.com
linkedin_username: dannyberghoff

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rogue
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
